# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-10-01 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.ImageField(upload_to='ad/%Y/%m', verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='careercourse',
            name='image',
            field=models.ImageField(upload_to='course/%Y/%m', verbose_name='课程小图标'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course/%Y/%m', verbose_name='课程封面'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='download_url',
            field=models.FileField(upload_to='course/%Y/%m', verbose_name='下载地址'),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='download_url',
            field=models.FileField(upload_to='lesson/%Y/%m', verbose_name='下载地址'),
        ),
        migrations.AlterField(
            model_name='links',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='links/%Y/%m', verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='mymessage',
            name='action_type',
            field=models.CharField(choices=[('1', '系统消息'), ('2', '课程讨论回复'), ('3', '论坛讨论回复')], max_length=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='recommendedreading',
            name='reading_type',
            field=models.CharField(choices=[('AV', '官方活动'), ('NW', '开发者资讯'), ('DC', '技术交流')], default='AV', max_length=2, verbose_name='文章类型'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_middle_thumbnall',
            field=models.ImageField(blank=True, default='avatar/default_middle.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='头像104x104'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_small_thumbnall',
            field=models.ImageField(blank=True, default='avatar/default_small.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='头像70x70'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.ImageField(blank=True, default='avatar/default_big.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='头像220x220'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='用户是否被激活，未激活则不能使用', verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='是否能够登录管理后台', verbose_name='职员状态'),
        ),
    ]
